### ISSUE TITLE
Is there a simple way to crawl the dataset?

### ISSUE THREAD

**Issue by AtlantixJJ** [jerryli27/pixiv_dataset#2]
Thank you for sharing, I'm also interested in sketch colorization and I find your work here. I basically followed your instruction but PixivUtil seems to be unfriendly for downloading by `image_id`s. I scan through PixivUtil's instructions but still don't know how to apply your lists to PixivUtil.

Would you please give a more detailed instruction? It would be very helpful. Thanks.

**Comment by AtlantixJJ** [comment]
Okay I find a temporary solution from [here](https://github.com/Nandaka/PixivUtil2/issues/321), that is passing file lists directly from command line argument.

```python
import os
import sys

TYPE="colored_sketch_pair.csv"
fids = open("pixiv_dataset/"+TYPE, "r").read()
fids = fids.replace("\n", " ").replace(",", " ")

print(fids[:100])

os.system("python PixivUtil2.py -x -s 2 " + fids)
```

**Comment by jerryli27** [comment]
Cool! If that's working, can I add your piece of code to the readme?

**Comment by AtlantixJJ** [comment]
Of course you can.

It works. I checked a few sketches and images. The content is correct, but they are placed in independent folders, and the naming is a mess. Probably I will write a script for post-processing.

One more thing: account information in `PixivUtil` should be filled in order to use this script.

**Comment by AtlantixJJ** [comment]
Besides, do you have a recommendation for learning materials or paper list for sketch colorization? I'm particularly interested in the identity of colorization, that is keeping the same person consistent.

**Comment by jerryli27** [comment]
One way to separate out the sketches and images without changing the PixivUtil2 source code is to change the settings in config.ini .
For example, I would change those three lines:
```
filenameformat = %image_id%
filenamemangaformat = %image_id%
filenameinfoformat = %image_id%
```
That way instead of naming the file by artist and artwork name, you get files with image id as their names. Then you can easily separate the sketch and colored images using the image-id list from csv file. The related section in the source code is 

```
PixivHelper.py

def makeFilename(nameFormat, imageInfo, artistInfo=None, tagsSeparator=' ', tagsLimit=-1, fileUrl='',
                 appendExtension=True, bookmark=False, searchTags=''):
    '''Build the filename from given info to the given format.'''
    if artistInfo is None:
        artistInfo = imageInfo.artist
...
```

As of the papers, I would recommend this one:
[Style Transfer for Anime Sketches with Enhanced Residual U-net and Auxiliary Classifier GAN](https://arxiv.org/abs/1706.03319)
Note that the newest version does not use the method described in the paper. Please also check
https://github.com/lllyasviel/style2paints
I also recommend this one:
http://paintschainer.preferred.tech/
https://github.com/pfnet/PaintsChainer
Related blog: [Using Chainer to color sketches yields surprising results (Translated)](https://qiita.com/jerryli27/items/f526a7d5b69ae758a3a6)

There are some other papers with less impressive results and different methods. And there are more papers that are not exactly colorization but closely related. You can read them if you have time
[Comicolorization  Semi-automatic Manga Colorization](https://arxiv.org/abs/1706.06759)
[Create Anime Characters with A.I.](https://makegirlsmoe.github.io/assets/pdf/technical_report.pdf)

**Comment by jerryli27** [comment]
Closing the issue due to lack of activity. Please reopen if needed.

**Comment by Yoposoc** [comment]
Hi, I'm actually interested in this. I can scrape image ids using something like downthemall, and then I used notepad++ to make a huge list of them with space delimiters. Can I use this almost as a "image_ids.txt" that I can feed into the program somehow?

It would be cool if it can download according to the order it's listed in the list.
